### ISSUE TITLE
dev: add endpoints for on-chain data

### ISSUE THREAD

**Issue by EvolveArt** [astraly-labs/pragma-node#38]
**Current Behavior**

The current `/data` endpoints return the data from the offchain DB which is filled by the kafka consumer service.
There is no endpoint to fetch we have from on-chain data.

**Expected Behavior**

We want to add a new `/onchain` base route that returns the data from the onchain DB.
This DB is currently hosted internally and filled through the [indexer service](https://github.com/Astraly-Labs/indexer-service).

**Comment by akhercha** [comment]
Checking this 👀
